name: "Tag stale issues and pull requests"

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v7
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue has been marked as stale because it has had no activity for 7 days. If you are still experiencing this issue, please comment or it will be closed in 7 days."
        stale-pr-message: "This pull request has been marked as stale because it has had no activity for 7 days. If you are still working on this, please comment or it will be closed in 7 days."
        days-before-stale: 7
        days-before-close: 7
        stale-issue-label: "stale"
        exempt-issue-labels: "keep-open"
        stale-pr-label: "stale"
        exempt-pr-labels: "keep-open"
        operations-per-run: 30
        debug-only: false
